//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinnerSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinnerSV.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Scommessa.
        /// </summary>
        public static string AddScommessaTitle {
            get {
                return ResourceManager.GetString("AddScommessaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner - Scommessa vincente.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenuItemDelete {
            get {
                return ResourceManager.GetString("ContextMenuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play new game.
        /// </summary>
        public static string PanoramaPivot1ItemTitle {
            get {
                return ResourceManager.GetString("PanoramaPivot1ItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedine.
        /// </summary>
        public static string PanoramaPivot2Header {
            get {
                return ResourceManager.GetString("PanoramaPivot2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PanoramaPivot3Header {
            get {
                return ResourceManager.GetString("PanoramaPivot3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver 1.0.0.0.
        /// </summary>
        public static string PivotAboutChangelogDescription {
            get {
                return ResourceManager.GetString("PivotAboutChangelogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string PivotAboutChangelogTitle {
            get {
                return ResourceManager.GetString("PivotAboutChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author ... privacy.
        /// </summary>
        public static string PivotAboutCreditsDescription {
            get {
                return ResourceManager.GetString("PivotAboutCreditsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string PivotAboutCreditsTitle {
            get {
                return ResourceManager.GetString("PivotAboutCreditsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App description.
        /// </summary>
        public static string PivotAboutDescription {
            get {
                return ResourceManager.GetString("PivotAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football.
        /// </summary>
        public static string SportsPivot1Header {
            get {
                return ResourceManager.GetString("SportsPivot1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        public static string SportsPivot2Header {
            get {
                return ResourceManager.GetString("SportsPivot2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string SportsPivot3Header {
            get {
                return ResourceManager.GetString("SportsPivot3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download ....
        /// </summary>
        public static string SportsProgressIndicatorText {
            get {
                return ResourceManager.GetString("SportsProgressIndicatorText", resourceCulture);
            }
        }
    }
}
